### ISSUE TITLE
The graphics driver did not installed successfully

### ISSUE THREAD

**Issue by cYpxHSx** [dartraiden/NVIDIA-WIn7-Win8-Signed-Driver#2]
Hello. I found your work and wanted to give it a try. I extracted the original files into a folder, replaced some files with your modded ones from the archive, and tried installing it. After restarting, I checked, and it gave me Error 52 in the Device Manager, just like the original installer. 

What can I do to fix that? I wanted to have the latest graphic drivers. But it won't work no matter what I tried unless I keep the OS in test mode. Any help will be appreciated. 

System specs;

i5 3570
16GB DDR3
NVIDIA GeForce GTX 960 (ZOTAC 4GB variant)
Gigabyte Z68P-DS3
1x 500GB and 2x 1TB HDD
Windows 7 Ultimate SP1, all updates installed including SHA-2.

**Comment by dartraiden** [comment]
Try to manually import dartraiden.cer from InstallCert directory.
Choose Trusted Root store during import.

**Comment by cYpxHSx** [comment]
Thanks for the response. I will try it like that. I wasn't sure where to put the InstallCert folder, so I put it in the root of the driver installer folder.

**Comment by cYpxHSx** [comment]
Hey. I wanted to make sure of something. You told me to do the certificate like this, yeah?

![new](https://github.com/user-attachments/assets/cdf082e7-f52b-4d98-8410-855c0e5da72d)

**Comment by dartraiden** [comment]
Yep

**Comment by cYpxHSx** [comment]
Okay, I did it... but it didn't work. Error 52 once again.

**Comment by dartraiden** [comment]
Check digital signature for nvlddmkm.sys

Is it valid?

**Comment by cYpxHSx** [comment]
![new](https://github.com/user-attachments/assets/14c3706d-bf54-4d72-9b74-7d5b9fccf67b)

I have this. Is this the one you are looking for?

**Comment by dartraiden** [comment]
Nope, look at file from releases

**Comment by dartraiden** [comment]
Now look at .cat file from releases

**Comment by cYpxHSx** [comment]
![new](https://github.com/user-attachments/assets/03b3a418-10a9-48e0-8d99-a23b28f5f00b)

Based on this, it does look like it is applied. But... is it really correct?

**Comment by dartraiden** [comment]
https://dl.dropboxusercontent.com/scl/fi/5jtk42rtjfz0p0cnbb0k7/test-475.14-desktop-win8-win7-64bit-international.zip?rlkey=d9azp7ciukng7v66o1sipyylz&dl=0

try this

**Comment by cYpxHSx** [comment]
Okay. Same method as manually installing the certificate into the Trusted?

**Comment by dartraiden** [comment]
Just replace files in official installer and run

**Comment by cYpxHSx** [comment]
![new](https://github.com/user-attachments/assets/3abdbd77-adf7-47d5-9789-266b6fe8f533)

Well, that worked. The weird thing is, that the installer hung on NVIDIA Shield progress, and I had to kill the task. But upon the restart, the file you gave me worked. Also, it's funny that it now shows as Athernos. I wonder if you can change that... or does it break the certificate?

**Comment by dartraiden** [comment]
> Also, it's funny that it now shows as Athernos

Because I use a leaked Ateros certificate for digital signature

**Comment by cYpxHSx** [comment]
Alright. Like I said, I will do a clean install and try again. I'll let you know in the edit.

**Comment by dartraiden** [comment]
Maybe the problem was caused by my mistakenly posting a link to a driver for Windows 10.
Make sure you downloaded 475.14-desktop-win8-win7-64bit-international.exe

**Comment by cYpxHSx** [comment]
Oh, I didn't download the wrong one. I am not that careless, lol

**Comment by cYpxHSx** [comment]
Okay, everything was installed correctly after a DDU attempt and a fresh install. Thank you so much for your help. I can now no longer need to worry about not having the GPU updated to the last.

One last thing, may I ask what was the reason compared to the one you posted in the release? I am curious on why it didn't work when I tried at first?

**Comment by dartraiden** [comment]
For some reason Windows wanted a valid signature not only on .cat, but also on .sys

**Comment by cYpxHSx** [comment]
I understand. You could consider updating your work so that others who are experiencing this similar issue can reference your new version. Additionally, I recommend updating your instructions to make them easier to follow for those with less technical expertise, because honestly, I didn't know that I had to install your certificate unless you pointed it out.

Thank you very much and have a good day.

**Comment by dartraiden** [comment]
The certificate is automatically installed by the installer, as we found out, the problem was not in it, but in .sys

**Comment by dartraiden** [comment]
Release updated.
